config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  resources :users
  resources :tutors
  resources :parents
  resources :reviews
  resources :childs
  resources :messages

  get "/dashboard", to: "pages#dashboard"
  get "/sign_in", to: "pages#sign_in"
  get "/sign_up", to: "pages#sign_up"
  get "/sign_up", to: "pages#sign_up"
  post "/sign_in", to: "sessions#create"
  delete '/sign_out', to: 'sessions#destroy'
end

app/models/child.rb
class Child < User
  belongs_to :parent
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/parent.rb
class Parent < User
  has_many :children
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/tutor.rb
class Tutor < User
  has_many :tutors
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, foreign_key: :tutor_id

  include Authem::User

  def full_name
    "#{first_name} #{last_name}"
  end

  def all_messages(tutor_id)
    messages = Message.where(parent_id: id)
    results = []
    messages = messages.order("created_at ASC")

    messages.each do |message|
      results << message if message.tutor_id == tutor_id
    end

    results

  end

  def children
    User.all.each_with_object([]) do |user, children|
      children << user if user.parent_id == id
    end
  end

  def average_rating
    n = 0
    sum = 0

    reviews.each do |review|
      sum += review.rating
      n += 1
    end

    if n != 0
      return (sum/n)
    else
      return 0
    end

  end

  def tutor_messages
  end

  def parent_messages
    possible_messages = Message.where(parent_id: id)
    messages = []
    possible_messages.each do |message1|
      possible_messages.each do |message2|
        messages << message2 if message1.tutor_id == message2.tutor_id
      end
    end
  end

  def messages_from
    messages = Message.where(parent_id: id)
    user_ids = []

    messages.each do |message|
      user_ids << message.tutor_id
    end

    user_ids = user_ids.uniq
    User.where(id: user_ids)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  authem_for :user
end

app/controllers/childs_controller.rb
class ChildsController < ApplicationController
  expose :child
  expose :new_child do
    User.new
  end

  expose :child_profile do
    User.find(params[:id])
  end

  expose :learning_styles do
    [ ["Select a learning style", ""], "Visual", "Listening", "Hands On", "N/A"]
  end


  def index
  end

  def show
  end

  private
  def child_params
    params.require(:child).permit(
      :comments,
      :first_name,
      :last_name,
      :learning_style
    )
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  expose :tutor do
    User.find(params[:tutor_id])
  end

  expose :new_message do
    Message.new
  end

  def index
  end

  def create
    message = Message.new(message_params)
    tutor_id = params[:message][:tutor_id]
    if message.save
      redirect_to message_path(message.id, tutor_id: tutor_id)
    else
      redirect_to new_messages_path(tutor_id: tutor_id)
    end
  end

  private
  def message_params
    params.require(:message).permit(
      :tutor_id,
      :parent_id,
      :body,
      :from_id
    )
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def sign_in
  end

  def sign_up
  end

  def dashboard
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  expose :review
  expose :tutor do
    User.find(params[:tutor_id])
  end

  def new
  end

  def create
    review = Review.new(review_params)
    tutor_id = params[:review][:tutor_id]
    if review.save
      redirect_to reviews_path(tutor_id: tutor_id)
    else
      redirect_to review_path(tutor_id: tutor_id)
    end
  end

  private
  def review_params
    params.require(:review).permit(
      :tutor_id,
      :parent_id,
      :rating,
      :body
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def destroy
    sign_out_user
    redirect_to :root
  end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  expose :days_of_week do
    { "Select availibility"=> "", Monday: "M", Teusday: "T", Wednesday: "W", Thursday: "R", Friday: "F", Saturday: "S", Sunday: "Sn"}
  end

  expose :tutor_list do
    tutors = User.where(kind: "Tutor")

    if params[:zipcode].present?
      tutors = tutors.where( zipcode: params[:zipcode] )
    end

    if params[:subject].present?
      tutors = tutors.where( subject: params[:subject] )
    end

    if params[:rating].present?
      results = []
      tutors.each do |tutor|
        results << tutor if tutor.average_rating >= params[:rating].to_i
      end

    end

    if params[:availibility].present?
      final = []

      if results.present?
        results.each do |tutor|
          tutor.availibility.each do |day|
            final << tutor if final.include?(day)
            break
          end
        end
      else
        tutors.each do |tutor|
          tutor.availibility.each do |day|
            if params[:availibility].include?(day)
              final << tutor
              break
            end
          end
        end
      end

    end

    if final.present? && results.present?
      final
    elsif final.present?
      final
    elsif results.present?
      results
    else
      tutors
    end
  end

  expose :subjects do
    [ ["Select a subject", ""], "Math", "Science", "Reading", "Spelling"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authem_for :user
  expose :user

  expose :qualifications do
    [ ["Select level of education", ""], "Highschool Diploma", "Pursuing Bachelors", "Pursuing Masters" ]
  end

  expose :subjects do
    [ ["Select a subject", ""], "Math", "Science", "Reading", "Spelling"]
  end

  expose :days_of_week do
    { "Select availibility"=> "", Monday: "M", Teusday: "T", Wednesday: "W", Thursday: "R", Friday: "F", Saturday: "S", Sunday: "Sn"}
  end

  def create
    user = User.new( user_params )

    if user.save
      if current_user.present?
        redirect_to child_path(user.id)
      else
        redirect_to root_path
      end
    else
      redirect_to new_user_path( type: "tutor" )
    end
  end

  def destroy
    sign_out_user
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(
      :bio,
      :kind,
      :email,
      :password,
      :password_confirmation,
      :first_name,
      :last_name,
      :qualifications,
      :bakckground_checked,
      :age,
      :grade,
      :parent_id,
      :zipcode,
      :filepicker_url,
      :comments,
      :learning_style,
      availibility: []
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/childs/index.html.haml
.container
  - if current_user.children.present?
    .tutors
      - current_user.children.each do |child|
        .tutor
          - if child.filepicker_url.present?
            = filestack_image( tutor.filepicker_url)
          - else
            = image_tag "default.jpg", class: "tutor_image"
          %p= child.full_name
          %p= "Learning Style: #{child.learning_style}"
          %p= child.email
          .links
      .tutor
        = link_to new_child_path do
          .holder
            %i.glyphicon.glyphicon-plus
  - else
    %h4
      Looks like you have no children signed up, add them!
      = link_to "Add child", new_child_path, class: "btn btn-primary"

app/views/childs/new.html.haml
.container
  .panel.panel-success
    .panel-heading
      %h4 Add Child to Family
    .panel-body
      = form_for new_child do |f|
        = f.hidden_field :parent_id, value: current_user.id
        .row
          .col-md-4
            = f.text_field :first_name, placeholder: "First name", class: "form-control"
          .col-md-4
            = f.text_field :last_name, placeholder: "Last name", class: "form-control"
          .col-md-4
            = f.select :learning_style, options_for_select( learning_styles ), {}, class: "form-control"

        %br
        .row
          .col-md-12
            = f.text_field :email, placeholder: "email@example.com", class: "form-control"

        %br
        .row
          .col-md-6
            = f.password_field :password, placeholder: "Password", class: "form-control"
          .col-md-6
            = f.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control"

        %br
        .row
          .col-md-12
            = f.trix_editor :comments, placeholder: "Comments on child's behavior"

        %br
        .row
          .col-md-12
            = f.submit "Save", class: "btn btn-success"

app/views/childs/show.html.haml
.container
  %h1= child_profile.full_name
  %p= child_profile.email
  %p
    %b Learning Style:
    = child_profile.learning_style
  %p
    %p
      %b Comments:
    = child_profile.comments.try(&:html_safe)

app/views/layouts/_footer.html.haml
.container
  %footer.footer
    %p © Tuteering! 2017

app/views/layouts/_nav.html.haml
.container
  %header.something
    %h3.text-muted= image_tag "whirlpool.png"
    %nav.navbar.navbar-expand-md.navbar-light.bg-light.rounded.mb-3
      %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarCollapse.collapse.navbar-collapse
        %ul.navbar-nav.text-md-center.nav-justified.w-100
          %li.nav-item{ class: params[:action] == "dashboard" ? "active" : ""}
            = link_to dashboard_path, class: "nav-link" do
              %i.glyphicon.glyphicon-home
              Home
            %span.sr-only (current)
          %li.nav-item{ class: params[:controller] == "tutors" ? "active" : ""}
            = link_to tutors_path, class: "nav-link" do
              %i.glyphicon.glyphicon-pencil
              Tutors
          %li.nav-item{ class: params[:controller] == "childs" ? "active" : ""}
            = link_to  childs_path, class: "nav-link" do
              %i.glyphicon.glyphicon-user
              Family

          %li.nav-item{ class: params[:controller] == "messages" ? "active" : ""}
            = link_to messages_path, class: "nav-link" do
              %i.glyphicon.glyphicon-envelope
              Messages
          %li.nav-item
            = link_to sign_out_path, method: :delete, class: "nav-link" do
              %i.glyphicon.glyphicon-log-out
              Sign Out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tuteering
    = filestack_js_include_tag
    = filestack_js_init_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    %link{href: "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", rel: "stylesheet"}
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css", :integrity => "sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp", :rel => "stylesheet"}/
    / Latest compiled and minified JavaScript
    %script{:src => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"}
    %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css", :rel => "stylesheet"}/




  = render "layouts/nav" if current_user.present?
  - if params[:action] == "new" && params[:controller] == "users"
    %body#special-body
      = yield
  - else
    %body
      = yield
  = render "layouts/footer" if current_user.present?

app/views/messages/_form.html.haml
= form_for new_message do |f|
  = f.hidden_field :tutor_id, value: tutor.id
  = f.hidden_field :from_id, value: current_user.id
  = f.hidden_field :parent_id, value: current_user.id
  = f.trix_editor :body, placeholder: "Hello #{tutor.full_name}..."
  %br
  = f.submit "Message", class: "btn btn-success"

app/views/messages/index.html.haml
.container
  .panel.panel-warning
    .panel-heading
      %h4 Messages
  .panel-body
    .tutors
      - current_user.messages_from.each do |tutor|
        .tutor
          - if tutor.filepicker_url.present?
            = filestack_image( tutor.filepicker_url)
          - else
            = image_tag "default.jpg", class: "tutor_image"
          %p
            = link_to tutor.full_name, message_path(current_user.id, tutor_id: tutor.id)
            = "(#{tutor.average_rating}/10)"
          %p= "Subject: #{tutor.subject}"
          %p= "Languages: English, Spanish"
          %p= tutor.email
          %p= "Zip code: #{tutor.zipcode}"

app/views/messages/show.html.haml
.container
  .panel.panel-success
    .panel-heading
      %h4= "Messages with #{tutor.full_name}"
    .panel-body
      .messages
        - current_user.all_messages(tutor.id).each do |message|
          .body= message.body.html_safe
          .from= User.find(message.from_id).full_name
        = render "form"

app/views/pages/_login_modal.html.haml
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        %h4#myModalLabel.modal-title Please Login
        .col-xs-8
          = form_tag "/sign_in" do
            .form-inputs
              %br
              .row
                .col-md-12
                  = label_tag :email
                  = text_field_tag :email, nil, class: "form-control"

              %br
              .row
                .col-md-12
                  = label_tag :password
                  = password_field_tag :password, nil, class: "form-control"
              %br
              = submit_tag "Sign In", class: "btn btn-success"

app/views/pages/dashboard.html.haml
!!!
%html{:lang => "en"}
  %head
    %title Tuteering - Parent Dashboard
  .container.dash
    %main{:role => "main"}
      / Jumbotron
      .jumbotron
        .row
          .col-lg-6
            %h2 Activity
            .activity
              %h3 Tutoring
              %p.detail
                Jimmmy has a tutoring date with Walter White coming up.
                = link_to "View event"
              %p.detail
                Kason has a tutoring date with Mr. Crocker coming up.
                = link_to "View event"
              %p.detail
                Sammy has a tutoring date with Mrs. Puff coming up.
                = link_to "View event"

              %h3 New Messages
              %p.detail
                Walter White sent you a
                = link_to "message"
              %p.detail
                Mr. Crocker sent you a
                = link_to "message"
              %p.detail
                Mrs. Puff sent you a
                = link_to "message"
              %h3 Misc
              %p.detail
                A new
                = link_to "tutor"
                has been added

            %P
          .col-lg-6
            %p
            .card{:style => "width: 100;"}
              %h1 Profile
              - if current_user.filepicker_url.present?
                .image= filestack_image current_user.filepicker_url
              - else
                .image= image_tag "profile.jpg", class: "example-img"
              .card-body
                %h4.card-title= current_user.full_name
                %p.card-text= current_user.bio

app/views/pages/home.html.haml
!!!
%html{:lang => "en"}
  %title Cover Template for Bootstrap
  %body#home
    .site-wrapper
      .site-wrapper-inner
        .cover-container
          %header.masthead.clearfix.home-mast
            .inner
              %h3.masthead-brand Tuteering!
              %nav.nav.nav-masthead
                %a.nav-link.active.home{"data-target" => "#myModal", "data-toggle" => "modal", :type => ""} Login

          %main.inner.cover{:role => "main"}
            = render "login_modal"
            .center
              = image_tag "whirlpool.png"
              %h2.cover-heading
                Volunteering
                %i.fa.fa-users
                + tutoring
                %i.fa.fa-graduation-cap
                is a perfect match
                %i.glyphicon.glyphicon-heart
              %p.lead A platform for a community of caring samaritans giving their time to tutor the students of tomorrow.
              .links
                %button.btn= link_to  "Register as Parent", new_user_path(type: "Parent")
                %button.btn= link_to "Register as Tutor", new_user_path(type: "Tutor")
              %p.lead
          %footer.mastfoot
            .inner

app/views/pages/sign_in.html.haml
.container
  .sign_in
    .panel.panel-success
      .panel-heading
        %h1 Sign In
      .panel-body
        = form_tag "/sign_in" do
          .form-inputs
            %br
            .row
              .col-md-12
                = label_tag :email
                = text_field_tag :email, nil, class: "form-control"

            %br
            .row
              .col-md-12
                = label_tag :password
                = password_field_tag :password, nil, class: "form-control"
            %br
            = submit_tag "Sign In", class: "btn btn-success"

app/views/pages/sign_up.html.haml
%h1 sign_up page

app/views/reviews/_form.html.haml
= form_for review do |f|
  = f.hidden_field :tutor_id, value: tutor.id
  = f.hidden_field :parent_id, value: current_user.id

  .form-inputs
    .row
      .col-md-12
        = f.label :body
        = f.trix_editor :body
    %br
    .row
      .col-md-3
        = f.label :rating
        = f.number_field :rating, max: 10, min: 1, class: "form-control"


    %br
    .row
      .col-md-12
        = f.submit "Submit", class: "btn btn-primary"

app/views/reviews/index.html.haml
.container
  .panel.panel-success
    .panel-heading
      %h2= "Reviews for #{tutor.full_name}"
  .reviews
    - if tutor.filepicker_url.present?
      .image= filestack_image tutor.filepicker_url
    - else
      .image= image_tag "default.jpg"
    - if tutor.reviews.present?
      - tutor.reviews.each do |review|
        .review
          = image_tag "default.jpg"
          = User.find(review.parent_id).first_name
          = review.body.html_safe
          = "Rating: #{review.rating}/10"
      .review.average
        %b Average rating:
        = "#{tutor.average_rating}/10"
    - else
      %h4.no-reviews
        There are no reviews from this user, be the first!
        = link_to "Review", new_review_path(tutor_id: tutor.id), class: "btn btn-primary"

app/views/reviews/new.html.haml
.container
  .panel.panel-success
    .panel-heading
      %h3= "Leave review for #{tutor.full_name}"
    .panel-body
      = render "form"

app/views/tutors/index.html.haml
.container
  .panel.panel-success
    .panel-heading
      %h4 Find Tutors
    .panel-body
      = form_tag "/tutors", method: "get" do
        .form-inputs
          %h4 Search
          .row
            .col-md-3
              = number_field_tag "zipcode", nil, min: 00000, max: 99999, class: "form-control", placeholder: "Search Zip Code"
            .col-md-3
              = select_tag "subject", options_for_select( subjects ),  class: "form-control"
            .col-md-3
              = number_field_tag "rating", nil, min: 0, max: 10,  class: "form-control", placeholder: "Lowest rating in search"
            .col-md-3
              = select_tag "availibility", options_for_select( days_of_week ), class: "form-control", placeholder: "Lowest rating in search", multiple: true
          %br
          = submit_tag "Search", class: "btn btn-success"
      %br

  - if tutor_list.blank?
    %h2 Sorry, no tutors match query
  - else
    .tutors
      - tutor_list.each do |tutor|
        .tutor
          - if tutor.filepicker_url.present?
            = filestack_image( tutor.filepicker_url)
          - else
            = image_tag "default.jpg", class: "tutor_image"
          %p
            = tutor.full_name
            = "(#{tutor.average_rating}/10)"
          %p= "Subject: #{tutor.subject}"
          %p= "Languages: English, Spanish"
          %p
            Availibity:
            - tutor.availibility.each do |a|
              = a
          %p= tutor.email
          %p= "Zip code: #{tutor.zipcode}"
          .links
            = link_to "Reviews", reviews_path(tutor_id: tutor.id), class: "btn btn-primary btn-sm"
            = link_to "Message", message_path(current_user.id, tutor_id: tutor.id), class: "btn btn-success btn-sm"

          .full-width= link_to "Leave review", new_review_path(tutor_id: tutor.id), class: "btn btn-warning btn-sm"

app/views/users/_parent_form.html.haml
= form_for user do |f|
  = f.hidden_field :kind, value: "Parent"

  %br
  .form-inputs
    .row
      .col-md-6
        = f.text_field :first_name, placeholder: "First Name", class: "form-control"
      .col-md-6
        = f.text_field :last_name, placeholder: "Last Name", class: "form-control"

  %br
  .form-inputs
    .row
      .col-md-12
        = f.text_field :email, placeholder: "Email", class: "form-control"
  %br
  .form-inputs
    .row
      .col-md-6
        = f.label :age
        = f.number_field :age, class: "form-control"
      .col-md-6
        = f.label :zip_code
        = f.number_field :zipcode, class: "form-control", placeholder: "11223"

  %br
  = f.trix_editor :bio, class: "form-control", placeholder: "Tell us about yourself."

  %br
  .form-inputs
    .row
      .col-md-6
        = f.password_field :password, class: "form-control", placeholder: "Password"
      .col-md-6
        = f.password_field :password_confirmation, class: "form-control", placeholder: "Passord Confirmation"

  %br
  = f.filestack_field :filepicker_url, 'Upload Your Avatar!'
  %br

  %br
  = f.submit "Sign up", class: "btn btn-success"

app/views/users/_tutor_form.html.haml
= form_for user, class: "form-control" do |f|
  = f.hidden_field :kind, value: "Tutor"

  %br
  .form-inputs
    .row
      .col-md-4
        = f.text_field :first_name, placeholder: "First Name", class: "form-control"
      .col-md-4
        = f.text_field :last_name, placeholder: "Last Name", class: "form-control"
      .col-md-4
        = f.text_field :email, placeholder: "Email", class: "form-control"

  %br
  .row
    .col-md-4
      = f.label :subject
      = f.select :subject, options_for_select( subjects ), {}, class: "form-control"
    .col-md-4
      = f.label :qualifications
      = f.select :qualifications, options_for_select(qualifications), {}, class: "form-control"
    .col-md-4
      = f.label :availibility
      = f.select :availibility, options_for_select(days_of_week), {}, class: "form-control", multiple: true
  %br
  .form-inputs
    .row
      .col-md-6
        = f.label :age
        = f.number_field :age, class: "form-control"
      .col-md-6
        = f.label :zip_code
        = f.number_field :zipcode, class: "form-control", placeholder: "11223"

  %br
  = f.trix_editor :bio, class: "form-control", placeholder: "Tell us about yourself."

  %br
  .form-inputs
    .row
      .col-md-6
        = f.password_field :password, class: "form-control", placeholder: "Password"
      .col-md-6
        = f.password_field :password_confirmation, class: "form-control", placeholder: "Passord Confirmation"

  %br
  = f.submit "Sign up", class: "btn btn-success"

app/views/users/new.html.haml
.sign_up_forms
  = image_tag "whirlpool.png"
.container
  .sign_in
    .panel.panel-primary.special
      .panel-heading
        %h2 Sign up
      .panel-body
        - if params[:type] == "Tutor"
          = render "tutor_form"
        - else
          = render "parent_form"